a=input("Adın ne?")
print("merhaba",a)
b=input(("Soyadın ne?"))
print("Güzel soyisim",b)
c=input("kaç yaşındasın?")
print("ben senden büyüğüm",c)
d=input("hastalığın varmı")
print("Geçmiş olsun zor hastalıktır",d)
e=input("cinsiyet ne?")
print("doğru gir",e,"olmadığını biliyorum")
f=input("hangi okul?")
print("Güzel Okuldur",f)
g=input("tc kimlik no")
print(g,"bu başkasının değil demi")
h=input("pcnin ekran kartı nedir")
print("umarım daha iyisdi olur")
k=input("okudunmu yada okuyomusun?")
print("iyiymiş",k)
l=input("en sevdiğin film nedir?")
print("güzel film",l)
